site_name: project-1
repo_url: https://github.com/ebbeborg/udacity_project1
site_url:
site_description:
site_author: Ebbe Borg
edit_uri: edit/main/docs/
repo_name: ebbeborg/udacity_project1
copyright: Maintained by

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["project_1"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
